### ISSUE TITLE
مرکز ولایت غور

### ISSUE THREAD

**Issue by NabizadaAbida** [el-factory/afghanistan-provinces#18]
چغچران بعد ار سال ۱۳۹۳ به فیروزکوه تغییر نام پیدا کرده است. 

منبع: [خبرگزاری پژواک](https://pajhwok.com/fa/2014/04/21/%D9%85%D8%B1%DA%A9%D8%B2-%D9%88%D9%84%D8%A7%D9%8A%D8%AA-%D8%BA%D9%88%D8%B1-%D8%A8%D9%87-%D9%81%D9%8A%D8%B1%D9%88%D8%B2%DA%A9%D9%88%D9%87-%D9%85%D8%B3%D9%85%D9%89-%D8%B4%D8%AF/)

**Comment by NanoNulla** [comment]
#19
